# Generated by Django 5.2.3 on 2025-06-19 14:45

import imageapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EditedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to=imageapp.models.upload_path)),
                ('removed_bg_image', models.ImageField(blank=True, null=True, upload_to=imageapp.models.upload_path)),
                ('edited_image', models.ImageField(blank=True, null=True, upload_to=imageapp.models.upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
